pipeline {
 agent any

 stages {

  stage('Checkout Code') {
   steps {
    git 'https://your-repo-url'
   }
  }

  stage('Build Docker Image') {
   steps {
    sh 'docker build -t devops-demo .'
   }
  }

  stage('Run Ansible Deployment') {
   steps {
    sh 'ansible-playbook ansible/deploy.yml'
   }
  }

 }

}